// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig,env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    
  },
  datasource: {
    // for prisma migration commands, it uses DATABASE_URL from .env
    // url: env("DATABASE_URL"),
    // shadowDatabaseUrl: env("DIRECT_URL"), // Used for testing and development to create a temporary database for migrations
    
    url: env("DIRECT_URL"), // Use DIRECT_URL for runtime to connect to the database
  },
}); 
