# These are supported funding model platforms

# github: kushkumarkashyap7280  # Uncomment when GitHub Sponsors is set up
# open_collective: batiyoun  # Uncomment when Open Collective is set up
# ko_fi: kushkumar  # Uncomment when Ko-fi is set up
# patreon: batiyoun  # Uncomment when Patreon is set up
custom: ['https://www.buymeacoffee.com/kushkumar']

# Support Batiyoun development!
# Your sponsorship helps with:
# - Server costs and infrastructure
# - Security audits
# - Feature development
# - Documentation and community support
